from aiogram.fsm.state import State, StatesGroup

class Form(StatesGroup):
    SET_BALANCE = State()
    ADD_CATEGORY_NAME = State()
    ADD_CATEGORY_TYPE = State()
    DELETE_CATEGORY = State()
    ADD_INCOME_AMOUNT = State()
    ADD_INCOME_CATEGORY = State()
    ADD_EXPENSE_AMOUNT = State()
    ADD_EXPENSE_CATEGORY = State()
    ADD_WISH_TITLE = State()
    ADD_WISH_AMOUNT = State()
    ADD_WISH_DESCRIPTION = State()
    DELETE_WISH = State()
    WISHLIST_PAGINATION = State()
    ADD_WISHES_LIST = State()
    ADD_EXPENSE_DESCRIPTION = State()
    ADD_INCOME_DESCRIPTION = State()
    REPORT_START_DATE = State()
    REPORT_END_DATE = State()
    COMPARE_MONTHS = State()
    ADD_INCOME_LIST_DATE = State()
    ADD_INCOME_LIST_ITEMS = State()
    ADD_EXPENSE_LIST_DATE = State()
    ADD_EXPENSE_LIST_ITEMS = State()
    DELETE_TRANSACTION_SELECT = State()
    DELETE_MULTI_TRANSACTIONS = State()
